git clone --branch 0e62848 git@github.com:catkin/catkin_simple.git
git clone --branch 1b8eab2 git@github.com:ethz-asl/glog_catkin.git
git clone --branch 6f48c85 https://github.com/tu-darmstadt-ros-pkg/hector_gazebo
git clone --branch 2e0d245 git@github.com:MURDriverless/lidar_dev.git
git clone --branch 0342d90 git@github.com:MURDriverless/linefit_ground_segmentation.git
git clone --branch 7faf0f9 git@github.com:MURDriverless/mur_common.git
git clone --branch d57bbe4 git@github.com:MURDriverless/mursim.git
git clone --branch 121d312 git@github.com:MURDriverless/mursim_actuator.git
git clone --branch d9da07e https://github.com/MURDriverless/ouster_example
git clone --branch 5cf5830 git@github.com:MURDriverless/path_follower_ros.git
git clone --branch 60746ed git@github.com:MURDriverless/planner_exploratory.git
git clone --branch 53e2ce8 git@github.com:MURDriverless/slam.git
git clone --branch cb9a8da git@github.com:MURDriverless/localisation.git
git clone --branch 1bab9c8 git@github.com:MURDriverless/vision_opencv.git
