git clone --branch master git@github.com:catkin/catkin_simple.git
git clone --branch master git@github.com:ethz-asl/glog_catkin.git
git clone --branch kinetic-devel https://github.com/tu-darmstadt-ros-pkg/hector_gazebo
git clone --branch task-262-lidar-sim git@github.com:MURDriverless/lidar_dev.git
git clone --branch master git@github.com:MURDriverless/linefit_ground_segmentation.git
git clone --branch master git@github.com:MURDriverless/mur_common.git
git clone --branch master git@github.com:MURDriverless/mursim.git
git clone --branch master git@github.com:MURDriverless/mursim_actuator.git
git clone --branch master https://github.com/MURDriverless/ouster_example
git clone --branch develop git@github.com:MURDriverless/path_follower_ros.git
git clone --branch develop/0.1 git@github.com:MURDriverless/planner_exploratory.git
git clone --branch develop git@github.com:MURDriverless/slam.git
git clone --branch opencv4 git@github.com:MURDriverless/vision_opencv.git
